server:
  port: 8882
spring:
  application:
    name: config-client
  cloud:
    config:
      discovery:
        ####### 启用config server discovery,将通过(发现)查找配置服务器URL
        enabled: true
        ####### 用于定位config server的服务id
        service-id: config-server
      ####### 配置文件后半部分
      profile: dev
      ####### 配置文件前半部分    配置文件：feng-config-dev.yml
      name: feng-config
  ########### 整合rabbitMQ
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
management:
  endpoints:
    web:
      ########### 放开的端口，*代表所有，基础路径/actuator/*
      exposure:
        include: "*"